### ISSUE TITLE
Compatibility with RiskUI (Since update 0.5.2)

### ISSUE THREAD

**Issue by arukado-sama** [viliger2/ExtradimensionaItems#2]
Hello dear viliger2,

The mod seems not compatible with RiskUI since the update 0.5.2 which added "Adrenaline Core".
In fact this item adds something to the HP bar so I guess this is the issue.
When played with RiskUI it makes the entire HUD totally disappear.
When played without RiskUI everything is fine, but a lot of players uses RiskUI so maybe you should look into it.

Thanks in advance for your reply!

**Comment by viliger2** [comment]
Thanks for the report, I'll take a look today- tomorrow. In the meantime have you tried disabling UI elements in the config?

**Comment by arukado-sama** [comment]
I didn't try to disable specific elements of the RiskUI, but I guess the HP bar is the main issue regarding the effect of the new extradimensional item. However it makes the entire HUD disappear, even the difficulty, money, items, etc.

I will try to disable the Adrenaline HUD in your config file to see if it temporary fixes the issue.

**Comment by arukado-sama** [comment]
I can now confirm that disabling the Adrenaline HUD ("Disable Adrenaline HUD = true" in the config file or with RiskOfOptions) temporary fixes the issue. Also you have to restart the game for it to be enabled/disabled properly.

**Comment by viliger2** [comment]
Issue is fixed with 0.5.3. However, the UI portion of the item simply disables itself if it can't find some things that it needs to function (things that RiskUI removes). So if you are using RiskUI you won't be getting the level indicator for the item. I might add support for RiskUI in the future, but it is very low priority.
