### ISSUE TITLE
bro, PLEASE PLEASE PLEASE USE ACTUAL DESCRIPTIONS

### ISSUE THREAD

**Issue by PineappleCat22** [viliger2/ExtradimensionaItems#3]
i was doing a run just now and i got a void item im like ah chill and i pick it up, unbeknownst to me im playing a modded character that is low mobility and low attack speed so obv attack speed up items are pretty important for me and this was lategame so i have a good couple soldier's stims right and then sorcerer's pills drops and the description reads: "Grabbin' pills!" and im like ight and IT REPLACES MY STIMS AND RUINS THE RUN. PLEASE GOD AT LEAST PUT AN INDICATOR OF WHAT THE ITEM DOES AND WHAT IT REPLACES LIKE OTHER VOID ITEMS MY RUN WAS GOING SO WELL GOD 

my blood is on your hands. have a nice day

**Comment by viliger2** [comment]
I won't change the description, you can use BetterUI or whatever for that, vanilla items do the same thing. But I will add what it corrupts to the short description and will do the same in the future, if I make any more void items.
